/*
 * This file is generated by jOOQ.
 */
package com.github.prbpedro.accountmanager.domain;


import com.github.prbpedro.accountmanager.domain.tables.Account;
import com.github.prbpedro.accountmanager.domain.tables.AccountBalance;
import com.github.prbpedro.accountmanager.domain.tables.AccountTransaction;
import com.github.prbpedro.accountmanager.domain.tables.Bank;
import com.github.prbpedro.accountmanager.domain.tables.Currency;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>AC_DATABASE</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FKAWL1LRPNGB7H5KTG79ODEIC5W_INDEX_E = Indexes0.FKAWL1LRPNGB7H5KTG79ODEIC5W_INDEX_E;
    public static final Index PRIMARY_KEY_E = Indexes0.PRIMARY_KEY_E;
    public static final Index FKEA365BS21NVTP9ENUUYXIM4TI_INDEX_E = Indexes0.FKEA365BS21NVTP9ENUUYXIM4TI_INDEX_E;
    public static final Index FKLIXFD5D2QJUX0B3PEYPCPEOL1_INDEX_E = Indexes0.FKLIXFD5D2QJUX0B3PEYPCPEOL1_INDEX_E;
    public static final Index PRIMARY_KEY_E1 = Indexes0.PRIMARY_KEY_E1;
    public static final Index FKCRTHG890SSJVT69F4IUENU92P_INDEX_2 = Indexes0.FKCRTHG890SSJVT69F4IUENU92P_INDEX_2;
    public static final Index FKF9CEM1VWYK13W14X2WY2I7CK_INDEX_2 = Indexes0.FKF9CEM1VWYK13W14X2WY2I7CK_INDEX_2;
    public static final Index FKTDC7RHIN60BXAHWAN5FNWCSA6_INDEX_2 = Indexes0.FKTDC7RHIN60BXAHWAN5FNWCSA6_INDEX_2;
    public static final Index PRIMARY_KEY_2 = Indexes0.PRIMARY_KEY_2;
    public static final Index PRIMARY_KEY_1 = Indexes0.PRIMARY_KEY_1;
    public static final Index UNIQUE_CODE_INDEX_1 = Indexes0.UNIQUE_CODE_INDEX_1;
    public static final Index PRIMARY_KEY_5 = Indexes0.PRIMARY_KEY_5;
    public static final Index UNIQUE_CODE_CURRENCY_INDEX_5 = Indexes0.UNIQUE_CODE_CURRENCY_INDEX_5;
    public static final Index UNIQUE_ACCOUNT_CURRENCY_INDEX_5 = Indexes0.UNIQUE_ACCOUNT_CURRENCY_INDEX_5;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index FKAWL1LRPNGB7H5KTG79ODEIC5W_INDEX_E = Internal.createIndex("FKAWL1LRPNGB7H5KTG79ODEIC5W_INDEX_E", Account.ACCOUNT, new OrderField[] { Account.ACCOUNT.BANK_ID }, false);
        public static Index PRIMARY_KEY_E = Internal.createIndex("PRIMARY_KEY_E", Account.ACCOUNT, new OrderField[] { Account.ACCOUNT.ID }, true);
        public static Index FKEA365BS21NVTP9ENUUYXIM4TI_INDEX_E = Internal.createIndex("FKEA365BS21NVTP9ENUUYXIM4TI_INDEX_E", AccountBalance.ACCOUNT_BALANCE, new OrderField[] { AccountBalance.ACCOUNT_BALANCE.CURRENCY_ID }, false);
        public static Index FKLIXFD5D2QJUX0B3PEYPCPEOL1_INDEX_E = Internal.createIndex("FKLIXFD5D2QJUX0B3PEYPCPEOL1_INDEX_E", AccountBalance.ACCOUNT_BALANCE, new OrderField[] { AccountBalance.ACCOUNT_BALANCE.ACCOUNT_ID }, false);
        public static Index PRIMARY_KEY_E1 = Internal.createIndex("PRIMARY_KEY_E1", AccountBalance.ACCOUNT_BALANCE, new OrderField[] { AccountBalance.ACCOUNT_BALANCE.ID }, true);
        public static Index FKCRTHG890SSJVT69F4IUENU92P_INDEX_2 = Internal.createIndex("FKCRTHG890SSJVT69F4IUENU92P_INDEX_2", AccountTransaction.ACCOUNT_TRANSACTION, new OrderField[] { AccountTransaction.ACCOUNT_TRANSACTION.CURRENCY_ID }, false);
        public static Index FKF9CEM1VWYK13W14X2WY2I7CK_INDEX_2 = Internal.createIndex("FKF9CEM1VWYK13W14X2WY2I7CK_INDEX_2", AccountTransaction.ACCOUNT_TRANSACTION, new OrderField[] { AccountTransaction.ACCOUNT_TRANSACTION.SENDER_ID }, false);
        public static Index FKTDC7RHIN60BXAHWAN5FNWCSA6_INDEX_2 = Internal.createIndex("FKTDC7RHIN60BXAHWAN5FNWCSA6_INDEX_2", AccountTransaction.ACCOUNT_TRANSACTION, new OrderField[] { AccountTransaction.ACCOUNT_TRANSACTION.BENEFICIARY_ID }, false);
        public static Index PRIMARY_KEY_2 = Internal.createIndex("PRIMARY_KEY_2", AccountTransaction.ACCOUNT_TRANSACTION, new OrderField[] { AccountTransaction.ACCOUNT_TRANSACTION.ID }, true);
        public static Index PRIMARY_KEY_1 = Internal.createIndex("PRIMARY_KEY_1", Bank.BANK, new OrderField[] { Bank.BANK.ID }, true);
        public static Index UNIQUE_CODE_INDEX_1 = Internal.createIndex("UNIQUE_CODE_INDEX_1", Bank.BANK, new OrderField[] { Bank.BANK.CODE }, true);
        public static Index PRIMARY_KEY_5 = Internal.createIndex("PRIMARY_KEY_5", Currency.CURRENCY, new OrderField[] { Currency.CURRENCY.ID }, true);
        public static Index UNIQUE_CODE_CURRENCY_INDEX_5 = Internal.createIndex("UNIQUE_CODE_CURRENCY_INDEX_5", Currency.CURRENCY, new OrderField[] { Currency.CURRENCY.CODE }, true);
        public static Index UNIQUE_ACCOUNT_CURRENCY_INDEX_5 = Internal.createIndex("UNIQUE_ACCOUNT_CURRENCY_INDEX_5", AccountBalance.ACCOUNT_BALANCE, new OrderField[] { AccountBalance.ACCOUNT_BALANCE.ID, AccountBalance.ACCOUNT_BALANCE.CURRENCY_ID }, true);
    }
}
