/*
 * This file is generated by jOOQ.
 */
package com.github.prbpedro.accountmanager.domain.tables.records;


import com.github.prbpedro.accountmanager.domain.tables.AccountTransaction;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountTransactionRecord extends UpdatableRecordImpl<AccountTransactionRecord> implements Record7<Long, Timestamp, String, BigDecimal, String, Long, String> {

    private static final long serialVersionUID = 1660768846;

    /**
     * Setter for <code>AC_DATABASE.ACCOUNT_TRANSACTION.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>AC_DATABASE.ACCOUNT_TRANSACTION.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>AC_DATABASE.ACCOUNT_TRANSACTION.DATE_TIME</code>.
     */
    public void setDateTime(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>AC_DATABASE.ACCOUNT_TRANSACTION.DATE_TIME</code>.
     */
    public Timestamp getDateTime() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>AC_DATABASE.ACCOUNT_TRANSACTION.STATUS</code>.
     */
    public void setStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>AC_DATABASE.ACCOUNT_TRANSACTION.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>AC_DATABASE.ACCOUNT_TRANSACTION.VALUE</code>.
     */
    public void setValue(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>AC_DATABASE.ACCOUNT_TRANSACTION.VALUE</code>.
     */
    public BigDecimal getValue() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>AC_DATABASE.ACCOUNT_TRANSACTION.BENEFICIARY_ID</code>.
     */
    public void setBeneficiaryId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>AC_DATABASE.ACCOUNT_TRANSACTION.BENEFICIARY_ID</code>.
     */
    public String getBeneficiaryId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>AC_DATABASE.ACCOUNT_TRANSACTION.CURRENCY_ID</code>.
     */
    public void setCurrencyId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>AC_DATABASE.ACCOUNT_TRANSACTION.CURRENCY_ID</code>.
     */
    public Long getCurrencyId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>AC_DATABASE.ACCOUNT_TRANSACTION.SENDER_ID</code>.
     */
    public void setSenderId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>AC_DATABASE.ACCOUNT_TRANSACTION.SENDER_ID</code>.
     */
    public String getSenderId() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Timestamp, String, BigDecimal, String, Long, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Timestamp, String, BigDecimal, String, Long, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return AccountTransaction.ACCOUNT_TRANSACTION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return AccountTransaction.ACCOUNT_TRANSACTION.DATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AccountTransaction.ACCOUNT_TRANSACTION.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return AccountTransaction.ACCOUNT_TRANSACTION.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return AccountTransaction.ACCOUNT_TRANSACTION.BENEFICIARY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return AccountTransaction.ACCOUNT_TRANSACTION.CURRENCY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return AccountTransaction.ACCOUNT_TRANSACTION.SENDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getDateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getBeneficiaryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getCurrencyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getSenderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getDateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getBeneficiaryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getCurrencyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getSenderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountTransactionRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountTransactionRecord value2(Timestamp value) {
        setDateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountTransactionRecord value3(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountTransactionRecord value4(BigDecimal value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountTransactionRecord value5(String value) {
        setBeneficiaryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountTransactionRecord value6(Long value) {
        setCurrencyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountTransactionRecord value7(String value) {
        setSenderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountTransactionRecord values(Long value1, Timestamp value2, String value3, BigDecimal value4, String value5, Long value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountTransactionRecord
     */
    public AccountTransactionRecord() {
        super(AccountTransaction.ACCOUNT_TRANSACTION);
    }

    /**
     * Create a detached, initialised AccountTransactionRecord
     */
    public AccountTransactionRecord(Long id, Timestamp dateTime, String status, BigDecimal value, String beneficiaryId, Long currencyId, String senderId) {
        super(AccountTransaction.ACCOUNT_TRANSACTION);

        set(0, id);
        set(1, dateTime);
        set(2, status);
        set(3, value);
        set(4, beneficiaryId);
        set(5, currencyId);
        set(6, senderId);
    }
}
